{
 "title": "Amazon Help",
 "description": "customer satisfaction",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "# Amazon Help - Reputation analysis\n\nMonitoring X account @AmazonHelp"
   }
  },
  {
   "title": "Tweet Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(*)\nFROM tweets\nWHERE strftime('%s', date) * 1000 BETWEEN $__from AND $__to",
     "rawQueryText": "SELECT COUNT(*)\nFROM tweets\nWHERE strftime('%s', date) * 1000 BETWEEN $__from AND $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Sample tweets",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 3 },
   "targets": [
    {
     "queryText": "SELECT text, sentiment\nFROM tweets\nWHERE strftime('%s', date) * 1000 BETWEEN $__from AND $__to",
     "rawQueryText": "SELECT text, sentiment\nFROM tweets\nWHERE strftime('%s', date) * 1000 BETWEEN $__from AND $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Reputation",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT COUNT(*) as count,sentiment\nFROM tweets\nWHERE strftime('%s', date) * 1000 BETWEEN $__from AND $__to\nGROUP BY sentiment",
     "rawQueryText": "SELECT COUNT(*) as count,sentiment\nFROM tweets\nWHERE strftime('%s', date) * 1000 BETWEEN $__from AND $__to\nGROUP BY sentiment",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Medium Confidence",
   "type": "bargauge",
   "description": "Confidence of sentiment analysis",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "queryText": "SELECT confidence, date\nFROM tweets\nWHERE strftime('%s', date) * 1000 BETWEEN $__from AND $__to",
     "rawQueryText": "SELECT confidence, date\nFROM tweets\nWHERE strftime('%s', date) * 1000 BETWEEN $__from AND $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Crawled Tweets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 21 },
   "targets": [
    {
     "queryText": "SELECT COUNT(*) as count, date\nFROM tweets\nWHERE strftime('%s', date) * 1000 BETWEEN $__from AND $__to\nGROUP BY date",
     "rawQueryText": "SELECT COUNT(*) as count, date\nFROM tweets\nWHERE strftime('%s', date) * 1000 BETWEEN $__from AND $__to\nGROUP BY date",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last issues",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 31 },
   "targets": [
    {
     "queryText": "SELECT author_id,date, text\nfrom tweets\nwhere sentiment = 'negative'\nAND strftime('%s', date) * 1000 BETWEEN $__from AND $__to\norder by date desc\nLIMIT 10",
     "rawQueryText": "SELECT author_id,date, text\nfrom tweets\nwhere sentiment = 'negative'\nAND strftime('%s', date) * 1000 BETWEEN $__from AND $__to\norder by date desc\nLIMIT 10",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}