{
 "title": "Training dashboard",
 "description": "Dashbroad on training process",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Last training stats",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT *\nfrom training_results \nWHERE strftime('%s', start_time) * 1000 BETWEEN 1763544644783 AND 1764149444783\nLIMIT 1;",
     "rawQueryText": "SELECT *\nfrom training_results \nWHERE strftime('%s', start_time) * 1000 BETWEEN $__from AND $__to\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT eval_accuracy,\n    start_time\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN 1763544644783 AND 1764149444783;",
     "rawQueryText": "SELECT eval_accuracy,\n    start_time\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN $__from AND $__to;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Training process",
   "type": "table",
   "description": "Last 10 train process.",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT *\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN $__from AND $__to\norder by start_time desc\nLIMIT 10;",
     "rawQueryText": "SELECT *\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN $__from AND $__to\norder by start_time desc\nLIMIT 10;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Evaluation loss",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT eval_loss,start_time\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN 1763543975570 AND 1764148775570",
     "rawQueryText": "SELECT eval_loss,start_time\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN $__from AND $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Evaluation accuracy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT eval_accuracy,start_time\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN 1763543975570 AND 1764148775570",
     "rawQueryText": "SELECT eval_accuracy,start_time\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN $__from AND $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Training time (s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 31 },
   "targets": [
    {
     "queryText": "SELECT \n    (strftime('%s', end_time) * 1000 - strftime('%s', start_time) * 1000)/1000 AS time_ms,\n    start_time\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN 1763543975570 AND 1764148775570;",
     "rawQueryText": "SELECT \n    (strftime('%s', end_time) * 1000 - strftime('%s', start_time) * 1000)/1000 AS time_ms,\n    start_time\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN $__from AND $__to;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Evalutaion Sample/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 31 },
   "targets": [
    {
     "queryText": "SELECT eval_samples_per_second, start_time\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN $__from AND $__to;",
     "rawQueryText": "SELECT eval_samples_per_second, start_time\nFROM training_results\nWHERE strftime('%s', start_time) * 1000 BETWEEN $__from AND $__to;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}